### ISSUE TITLE
java.lang.IllegalArgumentException: Missing argument

### ISSUE THREAD

**Issue by arturmkr** [ngchianglin/2faAppEngineJava8#1]
While running following:
```
            String otpresult = TimeBaseOTP.generateOTP(CryptoUtil.hexStringToByteArray("ACBBUOZXLKCKD8RABXECJABAFD6R6EGE"));
            System.out.println(otpresult);

```
There is an exception:
```
java.lang.IllegalArgumentException: Missing argument
	at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:93)
	at sg.nighthour.crypto.TimeBaseOTP.generateOTP(TimeBaseOTP.java:76)
at LoginTest.test(LoginTest.java:71)
```

**Comment by ngchianglin** [comment]
Hi, 

The CryptoUtil.hexStringToByteArray() method will return null if the input string contains invalid hexadecimal characters. 

In this case, the input "ACBBUOZXLKCKD8RABXECJABAFD6R6EGE" contains characters such as "U", "O", "Z" etc... which are not valid hexadecimal characters.  

To generate a proper hexadecimal string as well as its equivalent base 32 encoded string (to be used in Google Authenticator),  you can use the utility program at https://github.com/ngchianglin/2faUtility/
The java command line program, GenerateOTPSecret, can create a hexadecimal string and its equivalent base 32 string. 

Let me know if this solves the issue. 

Regards,
Chiang Lin
